"""N4 -- the 2x2 photonic tensor core of ``examples/paper/ptc_hspice/test12.py``, with N1
substituted for its DACs.

What is the same and what is different
--------------------------------------
The **photonic netlist is byte-identical** to the one ``paper/ptc_hspice/test12.py`` writes: the same
``ps`` / ``mzi`` / ``pd`` differential-dot blocks, the same ``wdm1to2`` / ``splitter1to2`` /
``modm`` weight modulators, the same ``.mode`` / ``.freq`` / ``.source`` / ``.prob`` lines, the
same node names, the same numbers.  It is generated by the same code, reproduced here, and the
example checks it against ``paper/ptc_hspice/test12.sp`` character by character.
Optical results are therefore directly comparable with the published ones.

The **electronic netlist** replaces the sky130 BSIM4 DAC (``level=54``, two 7-bit interpolating
converters plus a CMOS switch per operand) with one Level-1 R-2R converter per operand, N1 in
``dac7_r2r_l1.sub``.  With ``--tia`` the detector front end is swapped as well, for N3's real
common-source TIA in place of the ideal 70 dB block of ``pd_level2``.  Nothing in the circuit
then needs a model more complicated than ``level=1``.

The point
---------
Everything in ``paper/ptc_hspice/`` is locked to a licensed simulator because of the foundry compact
models, not because of anything SPIPE does.  This is the same computation with the electronics
expressed in devices any SPICE-family engine can evaluate, so it is the version a native back
end can run.

Run it::

    python examples/derived/n4_ptc_dotproduct.py
    python examples/derived/n4_ptc_dotproduct.py --tia      # also swap in N3
"""

from __future__ import annotations

import argparse
import math
import os
import random
import sys
from typing import Dict, List, Tuple

import os as _os, sys as _sys
# Make `import spipe` work from a source checkout without installing.
# Walks up to the repo root and puts `src/` on the path; a pip-installed
# spipe takes precedence because this only appends if the import fails.
try:
    import spipe as _probe  # noqa: F401
except ImportError:
    _here = _os.path.dirname(_os.path.abspath(__file__))
    for _ in range(6):
        _cand = _os.path.join(_here, 'src')
        if _os.path.isdir(_os.path.join(_cand, 'spipe')):
            _sys.path.insert(0, _cand)
            break
        _here = _os.path.dirname(_here)

# `_common` lives in examples/, one directory up from this one, and is NOT a package.
# Without this the script only imports when the current directory happens to be
# examples/ -- so `python examples/derived/n1_dac.py` from the repo root, which is what
# examples/README.md tells you to run, died on ModuleNotFoundError.
_examples_dir = _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))
if _examples_dir not in _sys.path:
    _sys.path.insert(0, _examples_dir)

import torch

from _common import (add_common_arguments, banner, report_convergence, resolve_spice_exe,
                     set_config, work_dir)

from spipe import Circuit, config, electronic_register, electronic_reset
from spipe.photonic import FreeLightSpeed

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))

# --------------------------------------------------------------------- test12's constants
ACT_L = 200e-6
COEFF1 = 1e-3
NEFF = 2.35
R0 = 1e-3
MAG = 1.0
RLOAD = 10e3
STD = 0.05
FREQ_START, FREQ_END = 193.5e12, 193.5e12
NUM_CHANNEL = 2
SHAPE = (2, 2)

NBITS = 8
VCONTROL = 3.3        # digital level of the DAC bits: rail to rail, because the Level-1
                      # switches in switch_l1.sub run off a 3.3 V supply and a 1.8 V "high"
                      # would leave their PMOS partly on (the sky130 original uses 1.8 V
                      # devices, for which 1.8 V is rail to rail).
VMAX = 3.3            # DAC reference
NUM_EXPECT = 5
T_INTERVAL, T_TRANSIT = 10e-9, 1e-12
NUM_T = 100


# --------------------------------------------------------------------- photonic (verbatim)
def write_ddot_content(input_port: List[str], output_port: List[str], inner_node_prefix: str,
                       device_count: int, pd_model: str) -> Tuple[str, int]:
    n1, n2 = input_port
    n3, n4 = output_port
    content = (
        f"""
ps{device_count} {n2} {inner_node_prefix}_1 ps=-0.5pi
mzi{device_count + 1} {n1} {inner_node_prefix}_1 {inner_node_prefix}_2 {inner_node_prefix}_3 theta=0.25pi
pd{device_count + 2} {inner_node_prefix}_2 {n3} {pd_model} r0={R0} std={STD}
pd{device_count + 3} {inner_node_prefix}_3 {n4} {pd_model} r0={R0} std={STD}
"""
    )
    return content, device_count + 4


def write_modulator_content(input_port, output_port, active_port, inner_node_prefix,
                            device_count) -> Tuple[str, int]:
    content = (
        f"""
wdm1to{len(active_port)}_{device_count} {input_port} {''.join([f'{inner_node_prefix}_b_{i} ' for i in range(len(active_port))])}
wdm1to{len(active_port)}_{device_count + 1} {inner_node_prefix}_bsp {''.join([f'{inner_node_prefix}_a_{i} ' for i in range(len(active_port))])}
splitter1to{len(output_port)}_{device_count + 2} {inner_node_prefix}_bsp {' '.join([str(n) for n in output_port])}
"""
    )
    device_count += 3
    for i in range(len(active_port)):
        content += (f"modm{device_count} {inner_node_prefix}_b_{i}  "
                    f"{inner_node_prefix}_dummy_{2 * i} {inner_node_prefix}_a_{i} "
                    f"{inner_node_prefix}_dummy_{2 * i + 1} {active_port[i]} level1 "
                    f"coeff1={COEFF1} act_l={ACT_L} alpha = 1.0\n")
        device_count += 1
    return content, device_count


def photonic_section(pd_model: str) -> Tuple[str, int, List[str]]:
    device_count = 0
    content = ''
    for i in range(SHAPE[0]):
        for j in range(SHAPE[1]):
            block, device_count = write_ddot_content(
                [f'n{i}{j}_up', f'n{i}{j}_do'], [f'm{i}{j}_up', f'm{i}{j}_do'],
                f'nd{i}{j}', device_count, pd_model)
            content += block

    drives: List[str] = []
    for i in range(SHAPE[0]):
        ports = [f'nac_h{i}_c{c}' for c in range(NUM_CHANNEL)]
        drives.extend(ports)
        block, device_count = write_modulator_content(
            f'h_in{i}', [f'n{i}{j}_up' for j in range(SHAPE[1])], ports, f'nd_h{i}', device_count)
        content += block

    for j in range(SHAPE[1]):
        ports = [f'nac_v{j}_c{c}' for c in range(NUM_CHANNEL)]
        drives.extend(ports)
        block, device_count = write_modulator_content(
            f'v_in{j}', [f'n{i}{j}_do' for i in range(SHAPE[0])], ports, f'nd_v{j}', device_count)
        content += block

    # Trailing whitespace matters here only because this block is compared character by
    # character with the one paper/ptc_hspice/test12.py writes; the blanks are spelled out as `sp` so
    # that an editor that strips trailing whitespace cannot silently break the comparison.
    sp = ' '
    content += (
        f"\n    .mode neff={NEFF}\n"
        f"    .freq {FREQ_START} {FREQ_END} {NUM_CHANNEL}\n"
        f"    .source {chr(32).join([f'{MAG}@h_in{i}' for i in range(SHAPE[0])])} "
        f"{chr(32).join([f'{MAG}@v_in{j}' for j in range(SHAPE[1])])} power=0.005w eff=0.2\n"
        f"    .prob nd_h0_bsp n00_up{sp}\n"
        "    .end\n"
        f"{sp * 4}\n"
        f"{sp * 4}")
    return content, device_count, drives


# --------------------------------------------------------------------- electronic (N1)
def helper(codes: List[int]) -> Tuple[torch.Tensor, torch.Tensor]:
    formatted = [f'{code:0{NBITS}b}' for code in codes]
    bits = []
    for bit in range(NBITS):
        waveform = [0.0]
        for value in formatted:
            level = VCONTROL if value[-1 - bit] == '1' else 0.0
            waveform.extend([level, level])
        bits.append(waveform)
    ideal = [0.0]
    for code in codes:
        ideal.extend([code * VMAX / float(2 ** NBITS - 1)] * 2)
    return torch.tensor(bits), torch.tensor(ideal)


def time_grid() -> torch.Tensor:
    grid = [0.0]
    for index in range(NUM_EXPECT):
        grid.extend([T_TRANSIT + T_INTERVAL * index, T_INTERVAL + T_INTERVAL * index])
    return torch.tensor(grid)


def write_dac(output_port: str, t: torch.Tensor, v: torch.Tensor, index: int) -> str:
    content = f"\n* N1 R-2R DAC driving {output_port}\n"
    content += (f"x{index} vrefh vrefl "
                + ' '.join(f'd{index}_{bit}' for bit in range(NBITS))
                + f" vdd {output_port} s8bit_DAC_l1\n")
    for bit in range(NBITS):
        points = ' '.join(f'{float(t[k]):.12g} {float(v[bit][k]):.6g}' for k in range(len(t)))
        content += f"Vd{index}_{bit} d{index}_{bit} 0 PWL ({points})\n"
    return content


def build_netlist(path: str, pd_model: str, seed: int = 0) -> Tuple[str, str, Dict]:
    photonic, device_count, drives = photonic_section(pd_model)

    random.seed(seed)
    t = time_grid()
    codes = {port: [random.randint(0, 2 ** NBITS - 1) for _ in range(NUM_EXPECT)]
             for port in drives}

    electronic = f""".include {os.path.join(HERE, 'models_level1.spice')}
.include {os.path.join(HERE, 'switch_l1.sub')}
.include {os.path.join(HERE, 'dac7_r2r_l1.sub')}
.option numdgt=7 relv=1e-6 reli=1e-9 absv=1e-9 absi=1e-15
Vdd vdd 0 3.3
Vrefh vrefh 0 {VMAX}
Vrefl vrefl 0 0
"""
    ideals: Dict[str, torch.Tensor] = {}
    for index, port in enumerate(drives):
        bits, ideal = helper(codes[port])
        ideals[port] = ideal
        electronic += write_dac(port, t, bits, index)

    for i in range(SHAPE[0]):
        for j in range(SHAPE[1]):
            electronic += f"rl{i}{j}u m{i}{j}_up 0 {RLOAD}\n"
            electronic += f"rl{i}{j}d m{i}{j}_do 0 {RLOAD}\n"

    electronic += f".tran 0 {float(t[-1]):.12g} {NUM_T}\n"
    electronic += (".print tran "
                   + ''.join(f'v(m{i}{j}_up) v(m{i}{j}_do) '
                             for i in range(SHAPE[0]) for j in range(SHAPE[1])) + "\n")

    with open(path, 'w') as handle:
        handle.write('.electronic\n' + electronic + '\n.photonic' + photonic)
    return path, photonic, {'t': t, 'ideal': ideals, 'codes': codes, 'drives': drives}


#: The paper deck this example reproduces.  It used to live in ``test2/``; the released
#: layout puts it under ``examples/paper/``.  Both are tried so the check keeps working in
#: either checkout -- a stale path here would silently downgrade the byte comparison to
#: "skipped", which reads like a pass.
REFERENCE_DECK = [
    os.path.join(REPO, 'examples', 'paper', 'ptc_hspice', 'test12.sp'),
    os.path.join(REPO, 'test2', 'test12.sp'),
]


def check_photonic_identical(photonic: str) -> str:
    """Compare the generated photonic section with the one in the paper's ``test12.sp``."""
    reference = next((p for p in REFERENCE_DECK if os.path.exists(p)), None)
    if reference is None:
        return ('test12.sp not found at any of %s -- byte comparison skipped'
                % ', '.join(os.path.relpath(p, REPO) for p in REFERENCE_DECK))
    with open(reference) as handle:
        text = handle.read()
    if '.photonic' not in text:
        return 'test12.sp has no .photonic section -- comparison skipped'
    theirs = text.split('.photonic', 1)[1]
    mine = photonic
    # The pd model name is an *electronic* identifier consumed by the netlist writer, not a
    # photonic parameter, so normalise it before comparing.
    mine = mine.replace(' level4 ', ' level2 ')
    if mine == theirs:
        return ('IDENTICAL to the .photonic section of %s (byte for byte)'
                % os.path.relpath(reference, REPO))
    for index, (a, b) in enumerate(zip(mine, theirs)):
        if a != b:
            return (f'DIFFERS from {os.path.relpath(reference, REPO)} at character {index}: '
                    f'{mine[max(0, index - 30):index + 30]!r} vs '
                    f'{theirs[max(0, index - 30):index + 30]!r}')
    return (f'DIFFERS from {os.path.relpath(reference, REPO)} only in length: '
            f'{len(mine)} vs {len(theirs)} characters')


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    add_common_arguments(parser)
    parser.add_argument('--tia', action='store_true',
                        help="also substitute N3's real TIA (pd_level4) for the ideal block")
    args = parser.parse_args()

    directory = work_dir(args, 'n4_ptc_dotproduct')
    spice_exe = resolve_spice_exe(args)
    set_config(args, max_iter=20)

    pd_model = 'level2'
    if args.tia:
        from n3_tia import PD_LEVEL4
        electronic_reset()
        electronic_register('pd', 'level4', PD_LEVEL4)
        pd_model = 'level4'

    netlist, photonic, stimulus = build_netlist(
        os.path.join(directory, 'n4_ptc.sp'), pd_model)

    banner('N4  2x2 photonic tensor core with the Level-1 electronics substituted')
    print(f"  netlist  : {netlist}")
    print(f"  DAC      : s8bit_DAC_l1 (N1, R-2R, level=1 CMOS switches), "
          f"{len(stimulus['drives'])} instances")
    print(f"  front end: pd_{pd_model}"
          + ("  (N3, real common-source TIA)" if args.tia else "  (the shipped ideal block)"))
    print(f"  photonic : {check_photonic_identical(photonic)}")

    circuit = Circuit(netlist, spice_exe=spice_exe,
                      spice_wrk_dir=os.path.join(directory, 'tmp'),
                      spice_file_name='n4_ptc.sp',
                      power_node=['vrefh', 'vrefl', 'vdd'])
    prob_e, _, param_e, param_p, power = circuit.simulate()
    info = circuit.fixed_point_info

    print('\n  -- fixed point ---------------------------------------------------------------')
    report_convergence(info)
    print('      (feedback free -- no photocurrent reaches a modulator drive -- so this is the '
          'two\n      iteration case the paper describes, exactly as in paper/ptc_hspice/test12.py)')

    t = circuit.time
    print('\n  -- DAC accuracy at the modulator ports ---------------------------------------')
    grid = stimulus['t']
    lsb = VMAX / (2 ** NBITS - 1)
    worst = 0.0
    for index, port in enumerate(stimulus['drives']):
        ideal = stimulus['ideal'][port]
        errors = []
        for k in range(NUM_EXPECT):
            target = float(grid[2 * k + 2]) - 0.1 * T_INTERVAL
            sample = int(torch.argmin((t - target).abs()))
            errors.append(float(param_p[sample, index]) - float(ideal[2 * k + 1]))
        worst = max(worst, max(abs(e) for e in errors))
        print(f"      {port:14s} codes {stimulus['codes'][port]}  "
              f"max |error| = {max(abs(e) for e in errors) * 1e3:7.3f} mV "
              f"= {max(abs(e) for e in errors) / lsb:6.3f} LSB")
    print(f"      worst over all ports: {worst * 1e3:.3f} mV = {worst / lsb:.3f} LSB "
          f"(1 LSB = {lsb * 1e3:.3f} mV)")

    print('\n  -- dot-product output --------------------------------------------------------')
    freq = torch.linspace(FREQ_START, FREQ_END, NUM_CHANNEL)
    amplify = (2 * (1 / SHAPE[0]) ** 0.5 * (1 / SHAPE[1]) ** 0.5 * R0 * MAG ** 2 * RLOAD)
    # Compare at the *settled* instant of each operand, 90% of the way through its interval.
    # Sample 0 is not one of them: HSPICE starts from uic with every node at zero, so there the
    # detectors read nothing while the closed-form expression (which is a function of the drive
    # alone) still reads full scale, and the difference there says nothing about the circuit.
    settled = []
    for k in range(NUM_EXPECT):
        target_time = float(grid[2 * k + 2]) - 0.1 * T_INTERVAL
        settled.append(int(torch.argmin((t - target_time).abs())))
    print(f"      evaluated at the {len(settled)} settled operand instants "
          f"(t = {', '.join(f'{float(t[s]) * 1e9:.1f}' for s in settled)} ns)")
    if args.tia:
        print('      NOTE: with N3\'s real front end the numbers below are NOT expected to '
              'follow the\n      closed form.  The analytic expression assumes the shipped '
              'pd_level2, whose "70 dB ideal\n      opamp" has no supply rails and happily '
              'reports +-16 V; the photocurrents of this PTC\n      are up to 1 mA, so a '
              'front end with real rails clips.  That the two disagree is the\n      finding, '
              'not a bug: the published circuit drives its receiver far outside any real '
              'supply.')
    for i in range(SHAPE[0]):
        for j in range(SHAPE[1]):
            measured = prob_e[f'v(m{i}{j}_up)'] - prob_e[f'v(m{i}{j}_do)']
            target = torch.zeros(len(t))
            for c in range(NUM_CHANNEL):
                a = 2 * math.pi * float(freq[c]) * NEFF / FreeLightSpeed * ACT_L * COEFF1
                phi1 = a * param_p[:, i * NUM_CHANNEL + c]
                phi2 = a * param_p[:, (SHAPE[0] + j) * NUM_CHANNEL + c]
                target = target + amplify * torch.cos(phi1) * torch.cos(phi2)
            difference = (measured - target)[settled].abs()
            print(f"      ddot({i},{j}): simulated "
                  f"{', '.join(f'{float(measured[s]):+7.3f}' for s in settled)} V")
            print(f"                 analytic  "
                  f"{', '.join(f'{float(target[s]):+7.3f}' for s in settled)} V"
                  f"   max |difference| = {float(difference.max()) * 1e3:.3f} mV")

    print('\n  -- power ---------------------------------------------------------------------')
    for key, value in power.items():
        if value is None:
            print(f"      {key:12s} : not monitored")
        elif hasattr(value, 'shape'):
            print(f"      {key:12s} : mean {float(value.mean()) * 1e3:10.6f} mW, "
                  f"peak {float(value.abs().max()) * 1e3:10.6f} mW")
        else:
            print(f"      {key:12s} : {value}")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
